packages:
  - packages/tui/tui
  - apps/tui-cli

linkWorkspacePackages: false

peerDependencyRules:
  allowedVersions:
    typescript: '>=5 <7'

allowBuilds:
  esbuild: true
  '@deepseek-ai/dsh-subprocess-local@0.1.2-rc.1': true
  lefthook: false
  node-pty: true
  koffi: true
  '@google/genai': false
  protobufjs: false
  node-addon-require-builtin: false

patchedDependencies:
  ink@7.1.1: patches/ink@7.1.1.patch
